# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Website Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@master

#     - name: Set up Node.js version
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12.x'

#     - name: npm install, build, and test
#       run: |
#         cd website
#         npm install
#         npm run build --if-present
#         npm run test --if-present

#     - name: 'Deploy to Azure Web App'
#       uses: azure/webapps-deploy@v1
#       with:
#         app-name: 'motion-layout'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AzureAppService_PublishProfile_14fabb491e39459f842584f7a4b8c3b5 }}
#         package: .
